Repository streamr-dev/engine-and-editor, pull requests merged in 2018-04, with the labels that each got.

#401 chore: CORE-1264 : Update to java8
  Dockerfile
  Dockerfile.optimized
Labels: devops

#399 Core 1240 thumbnail
  .idea/runConfigurations/test_run_app.xml
  grails-app/controllers/com/unifina/controller/api/ProductApiController.groovy
  grails-app/domain/com/unifina/domain/marketplace/Product.groovy
  grails-app/migrations/changelog.groovy
  grails-app/migrations/core/2018-04-04-add-product-thumbnailurl.groovy
  grails-app/migrations/core/2018-04-04-test-data-products-subscriptions.groovy
  grails-app/services/com/unifina/service/ProductImageService.groovy
  grails-app/services/com/unifina/service/ProductService.groovy
  package.json
  rest-e2e-tests/products-api.js
  rest-e2e-tests/schemas/product.json
  rest-e2e-tests/streamr-api-clients.js
  rest-e2e-tests/test-data/blue.png
  src/java/com/unifina/provider/S3FileUploadProvider.java
  src/java/com/unifina/utils/ImageResizer.java
  src/java/com/unifina/utils/ImageVerifier.java
  test/unit/com/unifina/controller/api/ProductApiControllerSpec.groovy
  test/unit/com/unifina/service/ProductImageServiceSpec.groovy
  test/unit/com/unifina/utils/ImageResizerSpec.groovy
  test/unit/com/unifina/utils/ImageVerifierSpec.groovy
Labels: fixed

#405 CORE-1264 Fix travis
  .travis.yml
  Makefile
Labels: reviewed

#407 Core 1260 add owner to product
  grails-app/domain/com/unifina/domain/marketplace/Product.groovy
  grails-app/migrations/changelog.groovy
  grails-app/migrations/core/2018-04-09-add-owner-to-product.groovy
  grails-app/services/com/unifina/service/ProductService.groovy
  scripts/db-diff.sh
  test/unit/com/unifina/api/ProductListParamsSpec.groovy
  test/unit/com/unifina/domain/marketplace/ProductSpec.groovy
  test/unit/com/unifina/service/ProductImageServiceSpec.groovy
  test/unit/com/unifina/service/ProductServiceSpec.groovy
Labels: fixed

#411 CORE-1287: API endpoint for listing my products
  grails-app/conf/UrlMappings.groovy
  web-app/misc/swagger.json
Labels: reviewed

#416 Core 1285 no config streams
  grails-app/controllers/com/unifina/controller/api/StreamApiController.groovy
  grails-app/domain/com/unifina/domain/data/Stream.groovy
  scripts/lint-swagger
  test/unit/com/unifina/controller/api/StreamApiControllerSpec.groovy
  web-app/misc/swagger.json
Labels: fixed

#412 Findbugs
  src/java/com/unifina/feed/AbstractFeedProxy.java
  src/java/com/unifina/security/MyPolicy.java
  src/java/com/unifina/security/UserClassLoader.java
  src/java/com/unifina/security/UserJavaClassLoader.java
  src/java/com/unifina/serialization/SerializerImpl.java
  src/java/com/unifina/signalpath/ModuleOption.java
  src/java/com/unifina/signalpath/SignalPath.java
  src/java/com/unifina/signalpath/charts/Heatmap.java
  src/java/com/unifina/signalpath/remote/AbstractHttpModule.java
  src/java/com/unifina/signalpath/simplemath/RoundToStep.java
  src/java/com/unifina/signalpath/statistics/LinearRegression.java
  src/java/com/unifina/signalpath/statistics/LinearRegressionXY.java
  src/java/com/unifina/signalpath/streams/GetOrCreateStream.java
  src/java/com/unifina/signalpath/streams/SearchStream.java
  src/java/com/unifina/signalpath/trigger/PeakDetect.java
  src/java/com/unifina/signalpath/utils/Barify.java
  test/unit/com/unifina/service/MockUserDetailsService.java
Labels: fixed, reviewed

#415 CORE-1258: API endpoint for unpublishing free products
  grails-app/controllers/com/unifina/controller/api/ProductApiController.groovy
  grails-app/services/com/unifina/service/FreeProductService.groovy
  rest-e2e-tests/products-api.js
  rest-e2e-tests/streamr-api-clients.js
  test/unit/com/unifina/controller/api/ProductApiControllerSpec.groovy
  test/unit/com/unifina/service/FreeProductServiceSpec.groovy
  web-app/misc/swagger.json
Labels: reviewed

#414 CORE-1257: API endpoint for publishing free products
  grails-app/controllers/com/unifina/controller/api/ProductApiController.groovy
  grails-app/services/com/unifina/service/FreeProductService.groovy
  grails-app/services/com/unifina/service/PermissionService.groovy
  rest-e2e-tests/products-api.js
  rest-e2e-tests/schemas/product.json
  rest-e2e-tests/streamr-api-clients.js
  rest-e2e-tests/subscriptions-api.js
  src/java/com/unifina/api/ProductNotFreeException.java
  test/unit/com/unifina/controller/api/ProductApiControllerSpec.groovy
  test/unit/com/unifina/service/FreeProductServiceSpec.groovy
  web-app/misc/swagger.json
Labels: reviewed

#420 CORE-1232: add missing callback
  grails-app/services/com/unifina/service/ProductService.groovy
  test/unit/com/unifina/service/ProductServiceSpec.groovy
Labels: reviewed

#421 Core 1282 login redirect
  .idea/engine-and-editor-grailsPlugins.iml
  .idea/engine-and-editor.iml
  grails-app/conf/BuildConfig.groovy
  grails-app/controllers/com/unifina/controller/security/LoginController.groovy
  grails-app/controllers/com/unifina/controller/security/LoginRedirectValidator.groovy
  grails-app/views/login/_form.gsp
  test/functional/LoginRedirectSpec.groovy
  test/unit/com/unifina/controller/security/LoginRedirectValidatorSpec.groovy
Labels: fixed, reviewed

#425 CORE-1196: Expiration of subscription-linked permissions
  grails-app/domain/com/unifina/domain/security/Permission.groovy
  grails-app/migrations/changelog.groovy
  grails-app/migrations/core/2018-04-16-add-ends-at-field-to-permission.groovy
  grails-app/services/com/unifina/service/PermissionService.groovy
  grails-app/services/com/unifina/service/SubscriptionService.groovy
  test/integration/com/unifina/service/PermissionServiceIntegrationSpec.groovy
  test/unit/com/unifina/service/PermissionServiceSpec.groovy
  test/unit/com/unifina/service/SubscriptionServiceSpec.groovy
Labels: reviewed

#428 fix: CORE-1349 - Add missing library to docker image
  .dockerignore
  Dockerfile
Labels: devops

#424 CORE-1230: Remove troll user's products
  grails-app/conf/UrlMappings.groovy
  grails-app/controllers/com/unifina/controller/api/RemoveUsersProductsController.groovy
  grails-app/domain/com/unifina/domain/security/SecUser.groovy
  grails-app/services/com/unifina/service/ProductService.groovy
  grails-app/services/com/unifina/service/SubscriptionService.groovy
  src/sql/delete_all.sql
  test/integration/com/unifina/service/ProductServiceIntegrationSpec.groovy
  test/unit/com/unifina/controller/api/RemoveUsersProductsControllerSpec.groovy
  test/unit/com/unifina/domain/security/SecUserSpec.groovy
  test/unit/com/unifina/service/ProductServiceSpec.groovy
  web-app/misc/swagger.json
Labels: fixed

#427 CORE-1347: allow updating Blockchain info of undeployed Product
  grails-app/services/com/unifina/service/ProductService.groovy
  rest-e2e-tests/products-api.test.js
  src/groovy/com/unifina/api/UpdateProductCommand.groovy
  test/unit/com/unifina/api/UpdateProductCommandSpec.groovy
  test/unit/com/unifina/service/ProductServiceSpec.groovy
  web-app/misc/swagger.json
Labels: reviewed

#430 CORE-1354: add thumbnailUrl to Product#toMap
  grails-app/domain/com/unifina/domain/marketplace/Product.groovy
  rest-e2e-tests/products-api.test.js
  test/unit/com/unifina/service/ProductServiceSpec.groovy
  web-app/misc/swagger.json
Labels: reviewed

#435 CORE-1362: isFree boolean to Product#toMap
  grails-app/domain/com/unifina/domain/marketplace/Product.groovy
  rest-e2e-tests/products-api.test.js
  rest-e2e-tests/schemas/product.json
  test/unit/com/unifina/api/UpdateProductCommandSpec.groovy
  test/unit/com/unifina/service/ProductServiceSpec.groovy
Labels: reviewed
